site_name: AjaxUpload for MODX Revolution
docs_dir: core/components/ajaxupload/docs
site_dir: _build/site

repo_url: https://github.com/Jako/AjaxUpload

pages:
- [index.md, Home]
- [installation.md, Installation]
- [usage.md, Usage]
- [contributors.md, Contributors]
- [donate.md, Donate]

theme: readthedocs

markdown_extensions: [footnotes,tables]